### ISSUE TITLE
(*XMLReader).ReadTime chokes on VM creation_time (cannot parse "Z" as "-07:00")

### ISSUE THREAD

**Issue by slrz** [imjoey/ovirt-engine-sdk-go#116]
## The problem

When running a simple program to list VMs, the XMLReader's ReadTime method fails upon encountering a VM creation time using a Z to signify UTC (vs. a numeric offset like +00:00).
AFAICT, oVirt always uses a Z for the UTC timezone (matching ISO8601/RFC3339), so the existing code doesn't work on systems configured to use UTC.

Example fragment from the XML returned from /ovirt-engine/api/vms:
`<creation_time>2018-05-25T08:52:54.196Z</creation_time>`

Changing the format string to time.RFC3339Nano should resolve the issue.

## Environment
Happens with current master of the generated imjoey/go-ovirt package (e05f1dd based on generator commit 17ce010) but the code in question hasn't changed since the initial import.

## Steps to Reproduce

1. create VM with creation timestamp in UTC
2. run https://play.golang.org/p/KI_w0pK2Ex_o (adapted from example)

**Expected behavior:**
See "OK".

**Actual behavior:**
`parsing time "2018-05-25T08:52:54.196Z" as "2006-01-02T15:04:05.999999-07:00": cannot parse "Z" as "-07:00"`

**Comment by imjoey** [comment]
@slrz Nice work. This is absolutely a serious bug. Since the creation timestamp in my case is `<creation_time>2018-04-25T13:59:00.234+08:00</creation_time>`, I didn't consider the compatibility. I have changed the format string to `time.RFC3339Nano` as you mentioned, and all tests are OK. Please see PR #117 . Thanks.

**Comment by slrz** [comment]
Thanks, that fixes the issue. The format string is also used within the generator code but doesn't end up in the output. I guess this is because no date/time type is ever used as an XML attribute.

While that's not very likely to change in future model versions, it's probably best to just fix it there, too, lest someone trips over it at some point. See PR #118.

**Comment by slrz** [comment]
Issue should be resolved now. Thank you.
