### ISSUE TITLE
Remove the generated code from the repository

### ISSUE THREAD

**Issue by jhernand** [imjoey/ovirt-engine-sdk-go#19]
Most of the source code of the SDK is automatically generated from the specification of the API. Currently this generated code, the `types.go` and `services.go` files, is committed into the git repository. This may cause problems, because changes to the code generator can get out of sync with this code, if one forgets to re-generate and commit the result. In addition those files are huge, because they contain code for each and every service and type in the API. That bloats the repository, and reviewing changes to those files will be difficult and useless.

On the other hand having those files in the repository makes it possible to use the SDK like any typical Go library:

```go
import "github.com/imjoey/ovirt-engine-sdk-go"
```

That isn't possible if the generated code isn't committed into the repository.

To accommodate these two contradicting needs, I'd suggest to create two different git repositories:

* One git repository containing everything except the generated code. It could be named `ovirt-engine-sdk-go-generator`.

* Another one containing the generated code, but not the code generator. It could be this same repository, `ovirt-engine-sdk-go`.

Taking advantage of the Travis CI integration with GitHub we could maybe automatically update the `ovirt-engine-sdk-go` repository when changes are merged to the `ovirt-engine-sdk-go-generator` repository.

**Comment by jhernand** [comment]
@imjoey @machacekondra I'd appreciate your thoughts about this issue.

**Comment by imjoey** [comment]
@jhernand  This would be nice, which is clearer for library users and also simplifies the codes management for us. In contrast, there has no generated codes in the `sdk` directory of other oVirt sdks repositories. So I think splitting it to two repositories is necessary.

**Comment by imjoey** [comment]
@jhernand @machacekondra  About the names of the two repositories, it would be better to keep the `ovirt-engine-sdk-go` as the generator name, which is more idiomatic and the same as the names of  other sdks repositories . The new repository containing generated codes is less important than the generator one and its name could be something like `go-ovirt`, a much shorter one.

Please let me know your insights. Thanks.

**Comment by jhernand** [comment]
@imjoey Your suggestion seems reasonable to me, +1.

**Comment by imjoey** [comment]
@jhernand  The generated code has been removed from `sdk/ovirtsdk4` directory, and the sdk code will be deployed to [imjoey/go-ovirt](https://github.com/imjoey/go-ovirt) repository by Travis CI after a success build of a push/merge commit on master branch only. The pull request or commit on other branch will not trigger the deploying action.
