### ISSUE TITLE
Use a build pattern to create a connection

### ISSUE THREAD

**Issue by machacekondra** [imjoey/ovirt-engine-sdk-go#2]
Try to use the `builder` pattern for the creation of the
connection. Currently this SDK uses a long list of arguments, which is
bad for reading and complicates adding parameters. This is a common
issue in Go. The current way to create a connection is this:

```go
  conn, err := ovirtsdk4.NewConnection(
        inputRawURL, "admin@internal", "your-password",
        "", true, "", false,
        uint64(10*time.Second), true)
```

It is hard to say what the "" and true/false mean there, and it is
impossible to add new parameters without breaking the code that uses
that method. I'd suggest to have a `ConnectionBuilder` type, and then
create the connection like this:

```go
  conn, err := ovirtsdk4.NewConnectionBuilder().
          Url(inputRawUrl).
          User("admin@internal").
          Password("your-password).
          Build()
```

**Comment by imjoey** [comment]
@machacekondra this has been fixed in PR #6 .
