### ISSUE TITLE
Use getters and setters

### ISSUE THREAD

**Issue by machacekondra** [imjoey/ovirt-engine-sdk-go#4]
Access to attributes of types should be via getters (and maybe
setters, if the types are mutable), not via the members (those should
be private), because that way it is possible to do conversions and
generate good error messages when something doesn't work as expected.
For example, to access a VM name I think that the Vm type should have
at least two methods: NamePresent and Name. The first should check if
the name is really present, and the second should return it:

```go
  type Vm {
    ...
    name *string // Note that the name is a pointer, so that it
                 // can be nil, to indicate that there is no
                 // name.
    ...
  }

  func (v *Vm) NamePresent() bool {
    return v.name != nil
  }

  func (v *Vm) Name() string {
    if v.name == nil {
      panic("The attribute 'name' doesn't have a value")
    }
  }
```

Robust code should use this as follows:

```go
  vm = ...
  if vm.NamePresent() {
    fmt.Pritnf("name: %s\n", vm.Name())
  }
```

Less robust code will not do the check, and will crash, but at least
the error message will clearly indicate what was the problem.

Numbers should be represented using unlimited precision (big.Int, for
example) because some of them may be very, very large (who knows what
will be the disk size we will want to support in the future). For
those there should be methods to get/set the raw representatoin, and
also methods to get/set doing conversions:

```go
  type Vm {
    ...
    memory *big.Int
    ...
  }

  // To get the raw representation:
  func (v *Vm) Memory() *big.Int {
    return memory
  }

  // Convenience method if you know it is less than 32 bits:
  func (v *Vm) MemoryAsInt() int {
    // Check that it is really only 32 bits, then convert and
    // return it
  }
```

**Comment by imjoey** [comment]
@machacekondra , I use struct tags (e.g.: Architecture string   **`xml:"architecture"`**) to implement the xml deserialization to object, and in Go the attributes of deserialized object **MUST** be capitalized like Name, not name. So the attributes cannot be private, furthermore, the getter method name could only be "GetName()" instead of "Name()" which is more idiomatic in Go.
