### ISSUE TITLE
Use the builder pattern for requests

### ISSUE THREAD

**Issue by machacekondra** [imjoey/ovirt-engine-sdk-go#5]
Use the `builder` pattern for requests as well:

```go
  response, err := clustersService.List().
    Search("name=mycluster").
    Send()

  for _, cluster := range response.Clusters() {
    ...
  }
```

So the `List` method will actually be a builder for a `ListRequest`
object, and the `Send` method will be the equivalent to building and
sending it. The result should be a `ListResponse` object. The benefit
of this is again that parameters to the `List` methods can be added
without breaking backwards compatibility. Same for returned
parameters. In addition it is also possible to add in the future
variants of the `Send` method, for example `SendAsync`.

**Comment by imjoey** [comment]
fix it at commit 4aa718b, close it.
