### ISSUE TITLE
Support OAuth authentication

### ISSUE THREAD

**Issue by imjoey** [imjoey/ovirt-engine-sdk-go#51]
You are using HTTP basic authentication. That should work, but it is deprecated and may be removed in a future version of oVirt. I'd suggest you consider implementing OAuth authentication. Not an urgent thing, as it would make no difference in the contract that users of the SDK will see.

**Comment by Shashwatsh** [comment]
+1

**Comment by imjoey** [comment]
@Shashwatsh please see PR #83 .
