### ISSUE TITLE
How do i create a VM with this sdk? add examples

### ISSUE THREAD

**Issue by Shashwatsh** [imjoey/ovirt-engine-sdk-go#78]
Hi, i wanna create VM with this SDK but i see no examples for that?

**Comment by imjoey** [comment]
@Shashwatsh . PR #79 contains the `examples/add_vm.go` and `examples/add_vm_disk.go` examples. More VM related ones would be added soon. Thanks for your attention.

**Comment by imjoey** [comment]
@Shashwatsh PR #81 also contains some vm examples.

**Comment by Shashwatsh** [comment]
Cool!
